services:
  chat-service:
    build:
      context: ./backend/user/chat-service
      dockerfile: Dockerfile
    container_name: chat-service
    ports:
      - "5001:5001"
    env_file:
      - backend/user/chat-service/.env
    volumes:
      - ./backend/user/chat-service:/app
    command: ["python", "-m", "app.main"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    env_file:
      - frontend/.env
    volumes:
      - ./frontend:/app
    command: ["yarn", "run", "dev", "--host"]
