services:
  db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_DB: drchat
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

  chat-service:
    build:
      context: ./backend/user/chat-service
      dockerfile: Dockerfile
    container_name: chat-service
    ports:
      - "5001:5001"
    env_file:
      - backend/user/chat-service/.env
    volumes:
      - ./backend/user/chat-service:/app
    command: ["python", "-m", "app.main"]

  chat-history-service:
    build:
      context: ./backend/user/chat-history-service
      dockerfile: Dockerfile
    container_name: chat-history-service
    ports:
      - "5003:5003"
    env_file:
      - backend/user/chat-history-service/.env
    volumes:
      - ./backend/user/chat-history-service:/app
    command: ["python", "-m", "app.main"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    env_file:
      - frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  user-service:
    build:
      context: ./backend/user/user-service
      dockerfile: Dockerfile
    container_name: user-service
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg://app:secret@db:5432/drchat
    ports:
      - "5002:5002"
    volumes:
      - ./backend/user/user-service:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5002", "--reload"]

volumes:
  pgdata:
